config/routes.rb
GameContestServer::Application.routes.draw do
  resources :users
  resources :sessions, only:[ :new, :create, :destroy]
  resources :referees
  resources :contests do
    resources :players, shallow: true
    resources :matches, shallow: true, only:[ :index, :show]
  end
  

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  root 'users#index'

  

end

app/models/contest.rb
class Contest < ActiveRecord::Base
  belongs_to :user
  belongs_to :referee
  has_many :players
  has_many :matches, as: :manager
  validates :referee, presence: true
  validates :user, presence: true
  validates :name, presence: true, uniqueness: true
  validates :contest_type, presence: true
  validates :start, presence: true, :timeliness => {:on_or_after => :now, :type => :datetime}
  validates :deadline, presence: true, :timeliness => {:on_or_after => :now, :type => :datetime, :on_or_before => lambda { |record| record.start } }
  validates :description, presence: true
  
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_action :ensure_user_logged_in, only: [:new, :create, :edit, :update, :destroy]
  before_action :ensure_contest_creator, only: [:new, :create, :edit, :update]
  before_action :ensure_correct_user, only: [:edit, :update]
  
  
  def new
    @contest = current_user.contests.build
  end 
  
  def destroy
    @contest = Contest.find(params[:id])
    if current_user?(@contest.user) #|| current_user.admin?
      @contest.destroy
      flash[:success] = "Referee deleted."
      redirect_to contests_path
    else
      flash[:danger] = "Cannot delete contest."
      redirect_to root_path
    end 
  end
  
  def create
    @contest = current_user.contests.build(acceptable_params)
    if @contest.save then
      flash[:success] = "Contest #{@contest.name} created!"
      redirect_to @contest     
    else
      render 'new'
    end
  end
  
  def index
    @contests = Contest.all
  end
  
  def show
    @contest = Contest.find(params[:id])
  end
  
  def update
    if @contest.update_attributes(acceptable_params)
      flash[:success] = "Referee #{@contest.name} has been updated!"
      redirect_to @contest
    else
      render 'edit'
    end
  end
  
  def edit
  end
  
  
  
  private
    def acceptable_params
      params.require(:contest).permit(:referee_id, :name, :contest_type, :description, :start, :deadline)
    end
    
   def ensure_correct_user
       @contest = Contest.find(params[:id])
       redirect_to login_path, flash: { :danger => "Must be Logged in as correct user!" } unless current_user?(@contest.user)
    end
       
    def ensure_user_logged_in
     redirect_to login_path, flash: { :warning => "Error: please log in!" } unless logged_in? 
    end
    
    def ensure_contest_creator 
      redirect_to root_path, flash: { :danger => "Error: You are not a contest creator!" } unless current_user.contest_creator?
    end
    
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/views/contests/_contest.html.erb
<li><%= link_to contest.name, contest_path(contest) %>
  <% if current_user?(contest.user)%>
  | <%= link_to "edit", edit_contest_path(contest) %>
       | <%= link_to "delete", contest_path(contest), method: :delete, data: { confirm: "Are you sure you want to delete #{contest.name}?" } %><% end %></li>

app/views/contests/_contest_form.html.erb
 <% if @contest.errors.any? %>
    <div class="alert alert-danger"> 
    <p>There are <%= @contest.errors.count %> errors.</p>
    </div>
    <ul>
      <% @contest.errors.full_messages.each do |message| %>
      <li class="text-danger"> <%= message %> </li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "Name" %>
    <%= f.text_field :name, class: 'form-control'%>
  </div>
 
  <div class="form-group">
    <%= f.label :contest_type, "Contest Type" %>
    <%= f.text_field :contest_type, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= f.label :description, "Description" %>
    <%= f.text_field :description, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= f.label :start %>
    <%= f.datetime_select :start, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= f.label :deadline %>
    <%= f.datetime_select :deadline, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= f.label :referee_id, "Referee" %>
    <%= f.collection_select(:referee_id, Referee.all, :id, :name, class: 'form-control') %>
  </div>

app/views/contests/edit.html.erb
<% provide(:title, "Edit contest") %>
<h1>Update contest</h1>

<%= form_for @contest do |f| %>
  <%= render 'contest_form', f: f %>
  <%= f.submit 'Update Contest' %>
<%end %>

app/views/contests/index.html.erb
<% provide(:title, 'All Contests') %>
<h1>List of contests</h1>
<h2><%= @contests.length %> contests</h2>
<ul>
  <%= render @contests %>
</ul>

app/views/contests/new.html.erb
<% provide(:title, 'Create Contest!') %>
<h1>Create Contest!</h1>

<%= form_for @contest do |f| %>
  <%= render 'contest_form', f: f %>
  <%= f.submit 'Create Contest' %>
<% end %>

app/views/contests/show.html.erb
<% provide(:title, @contest.name) %>
<h1>Contest Information</h1>

<p>Name: <%= @contest.name %> | <%= link_to "edit", edit_contest_path(@contest) %> </p>
<ul>
  <li>Contest Creator: <%= link_to @contest.user.username, user_path(@contest.user) %></li>
  <li>Contest Type: <%= @contest.contest_type %></li>
  <li>Start Time: <%= distance_of_time_in_words_to_now(@contest.start) %></li>
  <li>Deadline: <%= distance_of_time_in_words_to_now(@contest.deadline) %></li>
  <li>Description: <%= @contest.description %></li>
  <li>Referee: <%= link_to @contest.referee.name, referee_path(@contest.referee) %></li>
  <li>Players: <ul><% @contest.players.each do |f| %>
    <li><%= link_to f.name, player_path(f) %></li><%end %></ul></li>
</ul>

<p><%= link_to "New Player", new_contest_player_path(@contest) %></p>

  