config/routes.rb
GameContestServer::Application.routes.draw do
  resources :users
  resources :sessions, only:[ :new, :create, :destroy]
  resources :referees
  resources :contests do
    resources :players, shallow: true
    resources :matches, shallow: true, only:[ :index, :show]
  end
  

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  root 'users#index'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :referees
  has_many :players
  has_many :contests
  has_secure_password
  validates :username, :presence => true, length: { maximum: 20 }, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_user_logged_in, only: [:edit, :update]
  before_action :ensure_correct_user, only: [:edit, :update]
  before_action :ensure_admin_user, only: [:destroy]
  before_action :ensure_not_logged_in, only: [:new, :create]
  respond_to :html, :json, :xml
  
  def index
    @users = User.all
    respond_with(@users)
  end
  
  def new
    @user = User.new
    respond_with(@user)
  end
  
  def create
    @user = User.new(user_params)
    if @user.save then
      log_in(@user)
      flash[:success] = "Welcome #{@user.username}"
    end
    respond_with(@user)
  end
    
  def destroy
    @user.destroy
    flash[:success] = "User deleted."      
    respond_with(@user)
  end
  
  def edit
  end
    
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Your account #{@user.username} was updated successfully!"
    end
    respond_with(@user)
  end
    
  def show
    @user = User.find(params[:id])
    respond_with(@user)
  end
    
  private
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
    
    def ensure_admin_user
      @user = User.find(params[:id])
      if !current_user.admin? || current_user?(@user)
        redirect_to root_path, flash: { :danger => "Error: Your must be an admin!" }
      end
    end
   
    def ensure_user_logged_in
     redirect_to login_path, flash: { :warning => "Error Unable, please log in!" } unless logged_in? 
    end
    
    def ensure_correct_user
      @user = User.find(params[:id])
      redirect_to root_path, flash: { :danger => "Error: please log in!" } unless current_user?(@user)
    end
    
    def ensure_not_logged_in
      redirect_to root_path, flash: { :warning => "Error!" } unless !logged_in?
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<li><%= link_to user.username, user_path(user) %> 
  <% if current_user && current_user.admin? && !current_user?(user) %>
    | <%= link_to "edit", edit_user_path(user) %>
       | <%= link_to "delete", user_path(user), method: :delete, data: { confirm: "Are you sure you want to delete #{user.username}?" } %><% end %></li>

app/views/users/_user_form.html.erb
  <% if @user.errors.any? %>
    <div class="alert alert-danger"> 
    <p>There are <%= @user.errors.count %> errors.</p>
    </div>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li class="text-danger"> <%= message %> </li>
      <% end %>
    </ul>
  <% end %>
  
  <div class="form-group">
    <%= f.label :username, "Username" %>
    <%= f.text_field :username, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= f.label :email, "Email" %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :chat_url, "Chat_Url" %>
    <%= f.text_field :chat_url, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password, "Password" %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>  
  </div>

app/views/users/_user_players.html.erb
<li><%= link_to player.name, player_path(player) %> |
     <%= link_to "edit", edit_player_path(player) %>
      <% if current_user?(player.user) %>
       | <%= link_to "delete", player_path(player), method: :delete, data: { confirm: "Are you sure you want to delete #{player.name}?" } %><% end %></li>

app/views/users/_user_referees.html.erb
<li><%= link_to referee.name, referee_path(referee) %> |
     <%= link_to "edit", edit_referee_path(referee) %>
      <% if logged_in? %>
       | <%= link_to "delete", referee_path(referee), method: :delete, data: { confirm: "Are you sure you want to delete #{referee.name}?" } %><% end %></li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<%= form_for @user do |f| %>
  <%= render 'user_form', f: f %>
  <%= f.submit 'Update account' %>
<%end %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>List of users</h1>
<h3><%= @users.length%> users</h3>
<ul>
  <%= render @users %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up!') %>
<h1>Sign up!</h1>

<%= form_for @user do |f| %>
  <%= render 'user_form', f: f %>
  <%= f.submit 'Create new account' %>
<%end %>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<h2>User Information</h2>
<p>Name: <%= @user.username %> | <%= link_to "edit", edit_user_path(@user) %></p>
<ul>
  <li>Email: <%= @user.email %></li>
  <li>Chat Url: <%= @user.chat_url %></li>
</ul>

<% if  @user.contest_creator? %>
<h2>Referees</h2>
<h4><%= @user.referees.length%> referees</h4>
<ul>
  <%= render partial: "user_referees", collection: @user.referees, as: :referee%>
</ul>
<p><%= link_to "New Referee", new_referee_path %></p>
<% end %>

<h2>Players</h2>
<h4><%=@user.players.length%> players</h4>
<ul>
  <%= render partial: "user_players", collection: @user.players, as: :player%>
</ul>