config/routes.rb
GameContestServer::Application.routes.draw do
  resources :users
  resources :sessions, only:[ :new, :create, :destroy]
  resources :referees
  resources :contests do
    resources :players, shallow: true
    resources :matches, shallow: true, only:[ :index, :show]
  end
  

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  root 'users#index'

  

end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :user
  belongs_to :contest
  has_many :matches, through: :player_matches
  has_many :player_matches
  validates :user,  presence: true
  validates :contest, presence: true
  validates :name, presence: true, uniqueness: {scope: :contest}
  validates :description, presence: true 
  validates :file_location, presence: true
  
  include Uploadable
  
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :ensure_user_logged_in, only: [:new, :create, :edit, :update, :destroy]
  before_action :ensure_correct_user, only: [:edit, :update]
  
  
  def new
    contest = Contest.find(params[:contest_id])
    @player = contest.players.build
  end 
  
  
  def create
    contest = Contest.find(params[:contest_id])
    @player = contest.players.build(acceptable_params)
    @player.user = current_user
    if @player.save then
      flash[:success] = "Referee #{@player.name} created!"
      redirect_to @player
    else
      render 'new'
    end
  end
  
  def index
    @players = Player.all
  end
  
  def show
    @player = Player.find(params[:id])
  end
  
  def update
    if @player.update_attributes(acceptable_params)
      flash[:success] = "Referee #{@player.name} updated successfully!"
      redirect_to @player
    else
      render 'edit'
    end
  end
  
  def edit
  end
  
  def destroy
    @player = Player.find(params[:id])
    if current_user?(@player.user) #|| current_user.admin?
      @player.destroy
      flash[:success] = "Player destroyed."
      redirect_to contest_players_path(@player.contest)
    else
      flash[:danger] = "Cannot delete player."
      redirect_to root_path
    end 
  end
  
  private
    def acceptable_params
      params.require(:player).permit(:contest_id, :name, :description, :upload, :downloadable, :playable)
    end
    
    def ensure_correct_user
      @player = Player.find(params[:id])
      redirect_to root_path, flash: { :danger => "Must be Logged in as correct user!" } unless current_user?(@player.user)
    end
   
    def ensure_user_logged_in
     redirect_to login_path, flash: { :warning => "Error: please log in!" } unless logged_in? 
    end
    
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_player.html.erb
<li><%= link_to player.name, player_path(player) %>
  <% if current_user?(player.user)%>   
  | <%= link_to "edit", edit_player_path(player) %>
       | <%= link_to "delete", player_path(player), method: :delete, data: { confirm: "Are you sure you want to delete #{player.name}?" } %><% end %></li>

app/views/players/_player_form.html.erb
 <% if @player.errors.any? %>
    <div class="alert alert-danger"> 
    <p>There are <%= @player.errors.count %> errors.</p>
    </div>
    <ul>
      <% @player.errors.full_messages.each do |message| %>
      <li class="text-danger"> <%= message %> </li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "Name" %>
    <%= f.text_field :name, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= f.label :downloadable, "Allow others to download this player" %>
    <%= f.check_box :downloadable, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :playable, "Allow others to compete against this player" %>
    <%= f.check_box :playable, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= f.label :description, "Description" %>
    <%= f.text_field :description, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= f.label :upload, 'Upload file' %>
    <%= f.file_field :upload, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= f.label :contest_id, "Contest" %>
    <%= f.collection_select(:contest_id, Contest.all, :id, :name, class: 'form-control') %>
  </div>

app/views/players/edit.html.erb
<% provide(:title, "Edit player") %>
<h1>Update player</h1>

<%= form_for @player do |f| %>
  <%= render 'player_form', f: f %>
  <%= f.submit 'Update Player' %>
<%end %>

app/views/players/index.html.erb
<% provide(:title, 'All players') %>
<h1>List of players</h1>
<h2><%=@players.length%> players</h2>
<ul>
  <%= render @players %>
</ul>

app/views/players/new.html.erb
<% provide(:title, 'Create Player') %>
<h1>Create Player</h1>

<%= form_for [@player.contest, @player] do |f| %>
  <%= render 'player_form', f: f %>
  <%= f.submit 'Create Player' %>
<%end %>

app/views/players/show.html.erb
<% provide(:title, @player.name) %>
<h2>Player Information</h2>

<p>Name: <%= @player.name %> | <%= link_to "edit", edit_player_path(@player) %></p>
<ul>
  <li>Creator: <%= link_to @player.user.username, user_path(@player.user) %></li>
  <li>Player is available for matches: <%= @player.playable %></li>
  <li>Player is downloadable: <%= @player.downloadable %></li>
  <li>Description: <%= @player.description %></li>
  <li>Contest: <%= link_to @player.contest.name, contest_path(@player.contest) %></li>
</ul>

<h2><%= "Match".pluralize(@player.contest.matches.count) %></h2>



<ul>
  <% @player.player_matches.each do |f| %>
    <li><%= f.result %> - <%= link_to f.match_id, match_path(f.match) %></li>
  <%end%>
  <li>Record: <%= @player.player_matches.wins.count %>-<%= @player.player_matches.losses.count %></li>
</ul>