config/routes.rb
GameContestServer::Application.routes.draw do
  resources :users
  resources :sessions, only:[ :new, :create, :destroy]
  resources :referees
  resources :contests do
    resources :players, shallow: true
    resources :matches, shallow: true, only:[ :index, :show]
  end
  

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  root 'users#index'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GameContestServer</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse" role="navigation">
    
    <div class="navbar-header">
      <ul class="nav navbar-nav">
        <li>
            <%= link_to "Game Contest Server", root_path %></li>
        <li <%= if current_page?(root_path) then 'class=active' end %>>
            <%= link_to "Home", root_path %></li>
        <li <%= if current_page?(users_path) then 'class=active' end %>>
              <%= link_to "Users", users_path %></li>
        <li <%= if current_page?(referees_path) then 'class=active' end %>>
              <%= link_to "Referees", referees_path %></li>
        <li <%= if current_page?(contests_path) then 'class=active' end %>>
              <%= link_to "Contests", contests_path %></li>
        <% if logged_in? %>
          <li <%= if current_page?(user_path(current_user)) then 'class=active' end %>>
              <%= link_to "Profile", user_path(current_user) %></li>
          <li <%= if current_page?(edit_user_path(current_user)) then 'class=active' end %>>
              <%= link_to "Settings", edit_user_path(current_user) %></li>
          <% if current_user.contest_creator? || current_user.admin? %>
            <li <%= if current_page?(new_referee_path) then 'class=active' end %>>
              <%= link_to "Create Referee", new_referee_path %></li>
            <li <%= if current_page?(new_contest_path) then 'class=active' end %>>
              <%= link_to "Create Contest", new_contest_path %></li>
          <% end %>
          <div class="navbar-header pull-right">
            <ul class="nav navbar-nav" >
              <li><%= link_to "Log Out", logout_path,  method: :delete %></li>
            </ul>
          </div>
        <% else %>
          <li <%= if current_page?(signup_path) then 'class=active' end %>>
            <%= link_to "Sign Up", signup_path %></li>
          <li <%= if current_page?(login_path) then 'class=active' end %>>
            <%= link_to "Log In", login_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>

  <% flash.each do |level, message| %>
    <div class="alert alert-<%= level %>"%><%= message %></div>
  <% end %>
  
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>